import Head from "next/head";
import Layout from "@/layout";

export default function Main({ children, metaTitle, metaDescription }) {
  return (
    <>
      <Head>
        <title>{`Learn Next - ${metaTitle}`}</title>
        <meta
          name="description"
          content={metaDescription || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="text-3xl font-bold underline">HomePage</div>
      </Layout>
    </>
  );
}
